name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./Portsea.Utils.sln
    - name: Build
      run: dotnet build ./Portsea.Utils.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish Portsea.Utils to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        # Filepath of the project to be packaged, relative to root of repository
        PROJECT_FILE_PATH: ./Portsea.Utils/Portsea.Utils.csproj
        # API key to authenticate with NuGet server
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
