name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./Portsea.Utils.sln
    - name: Build
      run: dotnet build ./Portsea.Utils.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    
    # Create the NuGet package in the folder from the environment variable NuGetDirectory
    - name: Create NuGet package
      run: dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}
    
    # Publish all NuGet packages to NuGet.org
    # Use --skip-duplicate to prevent errors if a package with the same version already exists.
    # If you retry a failed workflow, already published packages will be skipped without error.
    - name: Publish NuGet package
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json --api-key $NUGET_AUTH_TOKEN --skip-duplicate --no-symbols true
